package com.next.level.solutions.calculator.fb.mp.utils

import com.arkivanov.decompose.ComponentContext
import org.koin.core.parameter.ParametersDefinition
import org.koin.core.qualifier.Qualifier
import kotlin.reflect.KClass

class KoinFactory(
  val get: (clazz: KClass<*>, qualifier: Qualifier?, parameters: ParametersDefinition?) -> Any
) {
  inline fun <reified T> inject(): T = get.invoke(T::class, null, null) as T

  inline fun <reified R> componentOf(crossinline constructor: (ComponentContext) -> R, componentContext: ComponentContext): R = constructor(componentContext)
  inline fun <reified R, reified T1> componentOf(crossinline constructor: (ComponentContext, T1) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject())
  inline fun <reified R, reified T1, reified T2> componentOf(crossinline constructor: (ComponentContext, T1, T2) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11, reified T12> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11, reified T12, reified T13> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11, reified T12, reified T13, reified T14> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11, reified T12, reified T13, reified T14, reified T15> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11, reified T12, reified T13, reified T14, reified T15, reified T16> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11, reified T12, reified T13, reified T14, reified T15, reified T16, reified T17> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11, reified T12, reified T13, reified T14, reified T15, reified T16, reified T17, reified T18> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11, reified T12, reified T13, reified T14, reified T15, reified T16, reified T17, reified T18, reified T19> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11, reified T12, reified T13, reified T14, reified T15, reified T16, reified T17, reified T18, reified T19, reified T20> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11, reified T12, reified T13, reified T14, reified T15, reified T16, reified T17, reified T18, reified T19, reified T20, reified T21> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
  inline fun <reified R, reified T1, reified T2, reified T3, reified T4, reified T5, reified T6, reified T7, reified T8, reified T9, reified T10, reified T11, reified T12, reified T13, reified T14, reified T15, reified T16, reified T17, reified T18, reified T19, reified T20, reified T21, reified T22> componentOf(crossinline constructor: (ComponentContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22) -> R, componentContext: ComponentContext): R = constructor(componentContext, inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject(), inject())
}